version: '3.8'

services:
  kitsune:
    image: dovakiin0/kitsune:latest
    container_name: kitsune-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_PROXY_URL=http://proxy:4040
      - NEXT_TELEMETRY_DISABLED=1
    depends_on:
      proxy:
        condition: service_healthy
    networks:
      - kitsune-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

  proxy:
    image: dovakiin0/proxy-m3u8:latest
    container_name: kitsune-proxy
    restart: unless-stopped
    ports:
      - "4040:4040"
    environment:
      - PORT=4040
      - CORS_DOMAIN=kitsune:3000
      - NODE_ENV=production
    networks:
      - kitsune-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4040/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M

networks:
  kitsune-network:
    name: kitsune-network
    driver: bridge
